# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0fc0f3fc64acb7688339b9be30c0bdf2acc721af5b7801e94d6eecfdcaa57fb70d67a242b1f35cee65c72f2fe2aafa4e5b850721235d4f24ee26a9a256a34a9

test:
  secret_key_base: 1a5305d083f183da049f00dea6f114b9174933645ddbec2bf9f25f36c2eba3722610a9c0594d800e15567feed07e08de601be259ddb9ed535f9e5c1fc9b59b93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
